apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ project_slug }}-env
  labels:
    app.kubernetes.io/name: {{ project_slug }}
    app.kubernetes.io/component: secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ secret_store_name }}
    kind: {{ secret_store_kind }}
  target:
    name: {{ secret_name }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ secret_key }}
