apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dev-portal.fullname" . }}
  labels:
    {{- include "dev-portal.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "dev-portal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dev-portal.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 9000
          envFrom:
            - secretRef:
                name: app-secrets
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

        - name: nginx
          image: "{{ .Values.nginxImage.repository }}:{{ .Values.nginxImage.tag }}"
          ports:
            - containerPort: 80
            - containerPort: 443
