{{- if .Values.vault.enabled -}}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ include "dev-portal.fullname" . }}-vault
  labels:
    {{- include "dev-portal.labels" . | nindent 4 }}
spec:
  provider:
    vault:
      server: {{ .Values.vault.server | quote }}
      path: "secrets"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-secrets
  labels:
    {{- include "dev-portal.labels" . | nindent 4 }}
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: {{ include "dev-portal.fullname" . }}-vault
    kind: SecretStore
  target:
    name: app-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.vault.secretPath | quote }}
{{- end }}
