apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ project_slug }}
  labels:
    app.kubernetes.io/name: {{ project_slug }}
    app.kubernetes.io/component: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ project_slug }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ project_slug }}
        app.kubernetes.io/component: web
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: app
          image: {{ image_repository }}/app:{{ image_tag }}
          ports:
            - containerPort: 9000
          envFrom:
            - secretRef:
                name: {{ secret_name }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: "2"
              memory: 2Gi
          volumeMounts:
            - name: php-config-volume
              mountPath: /usr/local/etc/php/conf.d/memory-limit.ini
              subPath: php-memory-limit.ini
            - name: php-config-volume
              mountPath: /usr/local/etc/php-fpm.d/zzzz-access-log.conf
              subPath: php-fpm-access-log.conf
        - name: nginx
          image: {{ image_repository }}/nginx:{{ image_tag }}
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: php-config-volume
          configMap:
            name: php-config
        - name: nginx-config-volume
          configMap:
            name: nginx-config
