apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ project_slug }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ project_slug }}-web
                port:
                  number: 80
  tls:
    - hosts:
        - {{ domain }}
      secretName: {{ project_slug }}-tls
